theme: p2pparis
# baseURL: https://p2p.paris
title: Paris P2P

languageCode: en
DefaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: English
    params:
      locale: en_GB
      default_description: The Parisian community interested in all things P2P & Cryptography
      default_event_description: Paris P2P is a monthly meetup organized by and for the community passionate about P2P and cryptography. These meetups are free, informal afterworks, meant to encourage meetings and exchanges between developers, passionate and curious people, around a drink or open discussions.
      404_desc: Page not found
      404_cta: Go to homepage
    menu:
      main:
        - name: Events
          url: '/en/#events'
          weight: -100
        - name: About
          url: '/en/#about'
          weight: -90
        - name: Call for proposal
          url: '/en/#call-for-proposal'
          weight: -80
        - name: Meetup
          url: '#meetup'
          weight: -70
        - name: Discord
          url: '#discord'
          weight: -60
        - name: Github
          url: '#github'
          weight: -50
        - name: Contact
          url: '#contact'
          weight: -40
  fr:
    languageName: French
    params:
      locale: fr_FR
      default_description: La communauté parisienne intéressée par tout ce qui touche au P2P et à la cryptographie
      default_event_description: Paris P2P est un rendez-vous mensuel organisé par et pour la communauté des passionné.e.s de P2P et de cryptographie. Ces rendez-vous prennent la forme d’afterwork informels, gratuits, destinés à favoriser la rencontre et les échanges entre développeurs/développeuses, passionné.e.s et curieux/curieuses, autour d’un verre ou de discussions ouvertes.
      404_desc: Page introuvable
      404_cta: Aller à la page d'accueil
      months:
        1: 'janvier'
        2: 'février'
        3: 'mars'
        4: 'avril'
        5: 'mai'
        6: 'juin'
        7: 'juillet'
        8: 'août'
        9: 'septembre'
        10: 'octobre'
        11: 'novembre'
        12: 'décembre'
      months_short:
        1: 'janv'
        2: 'févr'
        3: 'mars'
        4: 'avr'
        5: 'mai'
        6: 'juin'
        7: 'juil'
        8: 'août'
        9: 'sept'
        10: 'oct'
        11: 'nov'
        12: 'déc'
      days:
        0: 'dimanche'
        1: 'lundi'
        2: 'mardi'
        3: 'mercredi'
        4: 'jeudi'
        5: 'vendredi'
        6: 'samedi'
      days_short:
        0: 'dim'
        1: 'lun'
        2: 'mar'
        3: 'mer'
        4: 'jeu'
        5: 'ven'
        6: 'sam'
    menu:
      main:
        - name: Événements
          url: '/fr/#events'
          weight: -100
        - name: À propos
          url: '/fr/#about'
          weight: -90
        - name: Envoyez vos sujets
          url: '/fr/#call-for-proposal'
          weight: -80
        - name: Meetup
          url: '#meetup'
          weight: -70
        - name: Discord
          url: '#discord'
          weight: -60
        - name: Github
          url: '#github'
          weight: -50
        - name: Contact
          url: '#contact'
          weight: -50

params:
  logo: /img/logo.png
  default_featured_image: /img/paris_p2p_thumbnail.jpg
  googleAnalyticsId: UA-124224137-5
  organization_name: P2P Paris
  email: bootstrap@p2p.paris
  meetup: https://www.meetup.com/France-P2P/
  twitter: https://twitter.com/ParisP2P
  github: https://github.com/francep2p
  discord: https://crpt.fyi/parisp2p-discord

imaging:
  resampleFilter: Linear
  quality: 90
